"""Eve adapter: emit a filesystem-first TypeScript agent project.

Eve keeps an agent's durable configuration in ``agent/``: instructions, skills,
schedules, and tools. Guardrails are emitted as TypeScript and every generated
agent exposes a ``runGuarded`` call site for tool and side-effect enforcement.
"""

from __future__ import annotations

import json

from .common import Emitter


def generate(spec, out_dir) -> list[str]:
    e = Emitter(out_dir)
    e.write("agent/agent.ts", _agent_ts(spec))
    e.write("agent/guardrails.ts", _guardrails_ts(spec))
    e.write("agent/instructions.md", _instructions_md(spec))
    e.write("package.json", _package_json(spec))
    e.write("README.md", _readme_md(spec))
    for skill in spec.skills:
        e.write(f"agent/skills/{skill['name']}.md", _skill_md(skill, spec))
    if spec.trigger.get("type") == "cron":
        e.write(f"agent/schedules/{spec.name}.ts", _schedule_ts(spec))
    if spec.mcp_servers:
        e.write("agent/tools/mcp-servers.json", _mcp_json(spec))
    return e.written


def _instructions_md(spec) -> str:
    sections = [f"# {spec.name}", spec.purpose]
    prompt = spec.system_prompt_text().strip()
    if prompt:
        sections.append(prompt)
    if spec.skills:
        sections.append(
            "Skills:\n"
            + "\n".join(
                f"- `{s['name']}`: {s['description']} "
                f"(see `agent/skills/{s['name']}.md`)"
                for s in spec.skills
            )
        )
    allowed_tools = spec.guardrails.get("allowed_tools")
    if allowed_tools:
        sections.append(
            "Tools: invoke only "
            + ", ".join(f"`{tool}`" for tool in allowed_tools)
            + "."
        )
    elif allowed_tools == []:
        sections.append("Tools: no tools are allowlisted.")
    side_effects = spec.guardrails["allowed_side_effects"]
    if side_effects:
        sections.append(
            "Side effects: only "
            + ", ".join(f"`{effect}`" for effect in side_effects)
            + f"; at most {spec.guardrails['max_actions']} per run."
        )
    else:
        sections.append("You are read-only: no side-effecting actions are allowed.")
    sections.append(
        "Guardrails are enforced mechanically by `runGuarded` in "
        "`agent/agent.ts`; do not bypass its stop-file, allowlist, budget, or "
        "receipt call sites."
    )
    return "\n\n".join(sections) + "\n"


def _agent_ts(spec) -> str:
    model = json.dumps(spec.model_for("eve"))
    return f'''/**
 * {spec.name} — generated by agent-forge (spec v1, runtime: eve).
 *
 * Guardrails are enforced by runGuarded below. Change the spec and regenerate;
 * do not remove the stop-file, allowlist, budget, or receipt call sites.
 */
import {{ defineAgent }} from "eve";

import {{ GUARDRAILS }} from "./guardrails";

export async function runGuarded<T>(
  toolName: string,
  action: () => Promise<T>,
  sideEffect?: string,
): Promise<T> {{
  try {{
    GUARDRAILS.checkStopFile();
    GUARDRAILS.checkTool(toolName);
    if (sideEffect) GUARDRAILS.requireSideEffect(sideEffect);
    const result = await action();
    GUARDRAILS.writeReceipt("ok", toolName);
    return result;
  }} catch (error) {{
    GUARDRAILS.writeReceipt("blocked", String(error));
    throw error;
  }}
}}

export default defineAgent({{
  model: {model},
}});
'''


def _guardrails_ts(spec) -> str:
    guardrails = spec.guardrails
    allowed_tools = guardrails.get("allowed_tools")
    receipt = guardrails.get("receipt", {}).get("path", "receipts/last.json")
    config = {
        "stopFile": guardrails["stop_file"],
        "allowedTools": allowed_tools,
        "allowedSideEffects": guardrails["allowed_side_effects"],
        "maxActions": guardrails["max_actions"],
        "receipt": receipt,
    }
    config_text = json.dumps(config, indent=2)
    return f'''/**
 * Mechanical guardrails for the generated Eve agent.
 *
 * Every tool/side-effect entry point must call checkStopFile, checkTool,
 * requireSideEffect, and writeReceipt through runGuarded in agent.ts.
 */
import {{ existsSync, mkdirSync, writeFileSync }} from "node:fs";
import {{ dirname, resolve }} from "node:path";

const CONFIG = {config_text} as const;

function matches(pattern: string, action: string): boolean {{
  return pattern.endsWith("/")
    ? action.startsWith(pattern)
    : pattern === action;
}}

class Guardrails {{
  private used = 0;

  checkStopFile(): void {{
    if (existsSync(resolve(process.cwd(), CONFIG.stopFile))) {{
      this.writeReceipt("paused", "stop file present");
      throw new Error(`guardrails: ${{CONFIG.stopFile}} is present`);
    }}
  }}

  checkTool(name: string): void {{
    if (
      CONFIG.allowedTools !== null &&
      !CONFIG.allowedTools.some((pattern) => matches(pattern, name))
    ) {{
      throw new Error(`guardrails: tool ${{name}} is not allowlisted`);
    }}
  }}

  requireSideEffect(action: string): void {{
    if (!CONFIG.allowedSideEffects.some((pattern) => matches(pattern, action))) {{
      throw new Error(`guardrails: side effect ${{action}} is not allowed`);
    }}
    if (this.used >= CONFIG.maxActions) {{
      throw new Error(`guardrails: action budget (${{CONFIG.maxActions}}) exhausted`);
    }}
    this.used += 1;
  }}

  writeReceipt(verdict: "ok" | "blocked" | "paused", note: string): void {{
    const target = resolve(process.cwd(), CONFIG.receipt);
    mkdirSync(dirname(target), {{ recursive: true }});
    writeFileSync(
      target,
      JSON.stringify({{ verdict, note, actions: this.used }}, null, 2) + "\\n",
      "utf8",
    );
  }}
}}

export const GUARDRAILS = new Guardrails();
'''


def _skill_md(skill, spec) -> str:
    if "body" in skill:
        body = skill["body"].strip()
    else:
        body = (spec.spec_dir / skill["file"]).read_text(encoding="utf-8").strip()
    return (
        f"---\nname: {skill['name']}\ndescription: {skill['description']}\n---\n\n"
        f"{body}\n"
    )


def _schedule_ts(spec) -> str:
    schedule = json.dumps(spec.trigger["schedule"])
    return f'''/** Generated from trigger.cron; do not hand-edit. */
import {{ defineSchedule }} from "eve/schedules";

export default defineSchedule({{
  cron: {schedule},
  markdown: {json.dumps(spec.purpose)},
}});
'''


def _mcp_json(spec) -> str:
    servers = {}
    for name, srv in spec.mcp_servers.items():
        entry = {"command": srv["command"]} if "command" in srv else {"url": srv["url"]}
        for key in ("args", "env", "headers"):
            if key in srv:
                entry[key] = srv[key]
        servers[name] = entry
    return json.dumps({"mcpServers": servers}, indent=2) + "\n"


def _package_json(spec) -> str:
    return json.dumps(
        {
            "name": spec.name,
            "private": True,
            "type": "module",
            "scripts": {"dev": "eve dev"},
            "dependencies": {"eve": "latest"},
        },
        indent=2,
    ) + "\n"


def _readme_md(spec) -> str:
    cron = ""
    if spec.trigger.get("type") == "cron":
        cron = (
            f"\nThe cron trigger is emitted at `agent/schedules/{spec.name}.ts`.\n"
        )
    mcp = ""
    if spec.mcp_servers:
        mcp = (
            "\nMCP declarations are emitted at "
            "`agent/tools/mcp-servers.json` for the Eve host's external-tool "
            "wiring.\n"
        )
    return f'''# {spec.name}

Generated by agent-forge (spec v1, runtime: eve). Do not hand-edit generated
files; change the spec and regenerate.

## Run

```bash
npm install
npm run dev
```

The always-on instructions live in `agent/instructions.md`; skills live in
`agent/skills/`. Guardrails are enforced by `runGuarded` in `agent/agent.ts`:
the stop file, tool and side-effect allowlists, action budget, and receipt are
all mechanical call sites.{cron}{mcp}'''.rstrip() + "\n"
