"""Durable conductor contracts and deterministic Phase 1 compilation."""

from .contracts import ContractError, validate_contract
from .fake_backend import (
    BackendHandle,
    BackendObservation,
    FakeBackend,
    LaunchCoordinator,
    LaunchDecision,
    TransientLaunchError,
    UnknownEffectError,
)
from .ledger import LedgerConflictError, LedgerCorruptionError, RunLedger, utc_now
from .orca import (
    OrcaBackend,
    OrcaClient,
    OrcaError,
    OrcaObserver,
    OrcaSettlementError,
    OrcaUnknownEffect,
)
from .recovery import (
    OrcaRecovery,
    RecoveryDecision,
    RecoveryError,
    RecoveryExecution,
    RecoveryObservation,
    RetryLaunch,
    decide_recovery,
    observation_from_worker_show,
)
from .reducer import RunState, TransitionError, WorkerState, reduce_event, reduce_events
from .scheduler import NodeSpec, Scheduler, SchedulerError, validate_plan
from .verticals import (
    PiLaunchCommand,
    RepoScoutLaunchReceipt,
    RepoScoutPlan,
    WebResearchPlan,
    VerticalSliceError,
    assert_workspace_unchanged,
    collect_repo_scout,
    collect_web_researcher,
    compile_pi_launch_command,
    compile_repo_scout,
    compile_web_researcher,
    fake_repo_scout_result,
    fake_web_research_result,
    launch_repo_scout,
    launch_web_researcher,
    snapshot_workspace,
    validate_repo_scout_result,
    validate_web_research_result,
)
from .resolver import ResolutionError, resolve_request

__all__ = [
    "BackendHandle",
    "BackendObservation",
    "ContractError",
    "FakeBackend",
    "LaunchCoordinator",
    "LaunchDecision",
    "LedgerConflictError",
    "LedgerCorruptionError",
    "OrcaBackend",
    "OrcaClient",
    "OrcaError",
    "OrcaObserver",
    "OrcaRecovery",
    "OrcaSettlementError",
    "OrcaUnknownEffect",
    "RecoveryDecision",
    "RecoveryError",
    "RecoveryExecution",
    "RecoveryObservation",
    "RetryLaunch",
    "ResolutionError",
    "RunLedger",
    "RunState",
    "utc_now",
    "TransitionError",
    "TransientLaunchError",
    "UnknownEffectError",
    "WorkerState",
    "decide_recovery",
    "observation_from_worker_show",
    "reduce_event",
    "reduce_events",
    "NodeSpec",
    "Scheduler",
    "SchedulerError",
    "validate_plan",
    "PiLaunchCommand",
    "RepoScoutLaunchReceipt",
    "RepoScoutPlan",
    "WebResearchPlan",
    "VerticalSliceError",
    "assert_workspace_unchanged",
    "collect_repo_scout",
    "collect_web_researcher",
    "compile_pi_launch_command",
    "compile_repo_scout",
    "compile_web_researcher",
    "fake_repo_scout_result",
    "fake_web_research_result",
    "launch_repo_scout",
    "launch_web_researcher",
    "snapshot_workspace",
    "validate_repo_scout_result",
    "validate_web_research_result",
    "resolve_request",
    "validate_contract",
]
