/**
 * hn-ai-sitter — generated by agent-forge (spec v1, runtime: eve).
 *
 * Guardrails are enforced by runGuarded below. Change the spec and regenerate;
 * do not remove the stop-file, allowlist, budget, or receipt call sites.
 */
import { defineAgent } from "eve";

import { GUARDRAILS } from "./guardrails";

export async function runGuarded<T>(
  toolName: string,
  action: () => Promise<T>,
  sideEffect?: string,
): Promise<T> {
  try {
    GUARDRAILS.checkStopFile();
    GUARDRAILS.checkTool(toolName);
    if (sideEffect) GUARDRAILS.requireSideEffect(sideEffect);
    const result = await action();
    GUARDRAILS.writeReceipt("ok", toolName);
    return result;
  } catch (error) {
    GUARDRAILS.writeReceipt("blocked", String(error));
    throw error;
  }
}

export default defineAgent({
  model: "openai-codex/gpt-5.4-mini",
});
