"""doc-assistant — generated by agent-forge (spec v1, runtime: langgraph).

Do not remove the GUARDRAILS wiring below: it is the spec's guardrails
section made mechanical. To change the policy, edit the spec's guardrails
and regenerate — or make the explicit decision to delete these call sites.
"""

from langchain.agents import create_agent
from langchain.chat_models import init_chat_model

from .guardrails import GUARDRAILS

from langchain_mcp_adapters.client import MultiServerMCPClient

MCP_SERVERS = {
    "filesystem": {
        "command": "npx",
        "args": [
            "-y",
            "@modelcontextprotocol/server-filesystem",
            "./docs"
        ],
        "transport": "stdio"
    }
}

PROMPT = 'Answer questions about the Markdown documents in ./docs using only what is actually in those files. Cite the file path for every claim.\n\nYou are doc-assistant. You answer questions about a folder of Markdown\ndocuments, exposed through your filesystem MCP tools.\n\nRules:\n\n- Answer only from files you have actually read this session.\n- Tool paths are relative to the docs root: list with `.` (not `./docs`),\n  read with just the file name (e.g. `sample.md`).\n- Cite the file path for every claim. No path, no claim.\n- If the docs do not contain the answer, say "not in the docs" and stop.\n- Never modify any file. You are read-only.\n\nTools: you may invoke only `read_file`, `read_text_file`, `list_directory`, `search_files`.\n\nYou are read-only: no side-effecting actions are allowed.'

async def graph():
    """Graph factory: connects to MCP servers at run time, not import time."""
    client = MultiServerMCPClient(MCP_SERVERS)
    tools = [GUARDRAILS.wrap(t) for t in await client.get_tools()]
    model = init_chat_model('anthropic:claude-sonnet-4-5')
    return create_agent(model=model, tools=tools, system_prompt=PROMPT)
